version: "3.9"

services:

  backend:
    build: ./backend
    container_name: superwatch_backend
    environment:
      - PORT=5000
    expose:
      - "5000"

  frontend:
    build: ./frontend
    container_name: superwatch_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend